version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - DOMAIN=http://192.168.1.216
      - SIGNUPS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - WEBSOCKET_ENABLED=false
      - LOG_LEVEL=debug
    volumes:
      - ./vw-data:/data
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
